# Generated by Django 6.1 on 2026-08-26 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('numero_tarjeton', models.PositiveIntegerField(unique=True)),
                ('propuesta', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='candidatos/')),
                ('es_voto_blanco', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['numero_tarjeton'],
            },
        ),
        migrations.CreateModel(
            name='EstadoElectoral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_activa', models.BooleanField(default=True, verbose_name='Jornada Activa')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Estado de la Elección',
            },
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votos', to='elecciones.candidato')),
            ],
        ),
    ]
