# Generated by Django 6.1 on 2026-09-24 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0003_cupos_tarjeton_5_y_6'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='activo',
            field=models.BooleanField(default=True, help_text='Desmárcalo para ocultar el cupo del tarjetón sin borrar sus votos.', verbose_name='Visible en el tarjetón'),
        ),
        migrations.AddField(
            model_name='estadoelectoral',
            name='hora_cierre_votacion',
            field=models.TimeField(default='16:00', help_text='Después de esta hora el administrador puede cerrar la jornada y habilitar los resultados.', verbose_name='Hora límite de votación'),
        ),
        migrations.AddField(
            model_name='estadoelectoral',
            name='resultados_publicos',
            field=models.BooleanField(default=False, help_text='Habilita la consulta de resultados para administradores y votantes.', verbose_name='Resultados publicados'),
        ),
    ]
