# Generated by Django 6.1 on 2026-09-25 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0005_tarjeton_cuatro_candidatos'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del plan')),
                ('eslogan', models.CharField(blank=True, max_length=250, verbose_name='Eslogan de campaña')),
                ('lema', models.CharField(blank=True, help_text='Frase corta que acompaña al eslogan, por ejemplo "Escuchar • Gestionar • Hacer seguimiento".', max_length=250, verbose_name='Lema')),
                ('vigencia', models.CharField(blank=True, max_length=60, verbose_name='Vigencia')),
                ('secciones', models.JSONField(blank=True, default=list, help_text='Lista de secciones estructuradas del documento.', verbose_name='Secciones del plan')),
                ('publicado', models.BooleanField(default=True, help_text='Si está desmarcado, el plan no se muestra en el micrositio.', verbose_name='Publicado')),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('candidato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan_trabajo', to='elecciones.candidato', verbose_name='Candidato')),
            ],
            options={
                'verbose_name': 'Plan de trabajo',
                'verbose_name_plural': 'Planes de trabajo',
            },
        ),
    ]
