# Generated by Django 6.1 on 2026-08-26 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Votante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(db_index=True, max_length=20, unique=True)),
                ('nombre_completo', models.CharField(max_length=150)),
                ('programa_o_dependencia', models.CharField(blank=True, max_length=150)),
                ('ingreso_registrado', models.BooleanField(default=False)),
                ('fecha_ingreso', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
