# Generated by Django 6.1 on 2026-09-24 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='votante',
            name='fecha_voto',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='votante',
            name='ya_voto',
            field=models.BooleanField(default=False, help_text='Se marca al registrar el voto. El voto sigue siendo secreto: no se guarda por quién votó.', verbose_name='Ya sufragó'),
        ),
    ]
