# Generated by Django 6.1 on 2026-09-24 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votantes', '0002_votante_fecha_voto_votante_ya_voto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='votante',
            options={'ordering': ['nombre_completo'], 'verbose_name': 'Votante', 'verbose_name_plural': 'Votantes del padrón'},
        ),
        migrations.AddField(
            model_name='votante',
            name='ficha',
            field=models.CharField(blank=True, db_index=True, max_length=30, verbose_name='Ficha'),
        ),
        migrations.AddField(
            model_name='votante',
            name='nivel_de_formacion',
            field=models.CharField(blank=True, max_length=40, verbose_name='Nivel de formación'),
        ),
        migrations.AddField(
            model_name='votante',
            name='primer_apellido',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='votante',
            name='primer_nombre',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='votante',
            name='segundo_apellido',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='votante',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('CC', 'Cédula de ciudadanía'), ('TI', 'Tarjeta de identidad'), ('CE', 'Cédula de extranjería'), ('PPT', 'Permiso por protección temporal')], max_length=10, verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='votante',
            name='documento',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Número de documento'),
        ),
        migrations.AlterField(
            model_name='votante',
            name='nombre_completo',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='votante',
            name='programa_o_dependencia',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
